### ISSUE TITLE
Support non-flat directory structure

### ISSUE THREAD

**Issue by notbandali** [bastibe/org-static-blog#10]
It would be nice to use `directory-files-recursively` instead of `directory-files` and allow subdirectories of arbitrary depth inside `org-static-blog-posts-directory`. This would allow having `example.com/2018/test.html` instead of e.g. `example.com/2018-test.html`.

**Comment by bastibe** [comment]
That's a great idea! Do you want to create a pull request and make sure that it works?

**Comment by aminb** [comment]
Sorry for the late reply; I've been swamped lately.

If I manage to find some free time I'll try to put together a PR and send it over, but otherwise, feel free to beat me to it :)

**Comment by bastibe** [comment]
Cool, no rush!

**Comment by geeklhem** [comment]
I had a crack at it. Here is a quick hack for the posts (not the drafts).

The trick is to use `directory-files-recursively` instead of `directory-file`

``` 
 (defun org-static-blog-get-post-filenames ()
   "Returns a list of all posts."
-  (directory-files
-   org-static-blog-posts-directory t ".*\\.org$" nil))
+  (directory-files-recursively
+   org-static-blog-posts-directory ".*\\.org$" nil))
 
 (defun org-static-blog-get-draft-filenames ()
   "Returns a list of all drafts."
```

Then we have to correctly match html files with the org-files.
The user is automatically prompted to create  non existing directories when `org-static-blog-publish` is called, thanks to some emacs' magic. 

```
@@ -147,13 +147,15 @@ re-rendered."
 (defun org-static-blog-matching-publish-filename (post-filename)
   "Generate HTML file name for POST-FILENAME."
   (concat org-static-blog-publish-directory
+	  (file-name-directory
+	   (file-relative-name post-filename org-static-blog-posts-directory))
           (file-name-base post-filename)
           ".html"))
```

The save function has to be slightly changed to keep the directory structure:
```
@@ -167,7 +169,9 @@ The buffer is disposed after the macro exits (unless it already
 existed before)."
   `(save-excursion
      (let ((current-buffer (current-buffer))
-           (buffer-exists (get-buffer (file-name-nondirectory ,file)))
+           (buffer-exists (get-buffer (concat
+				       (file-relative-name ,file org-static-blog-posts-directory)
+				       (file-name-nondirectory ,file))))
            (result nil))
        (if buffer-exists
            (switch-to-buffer buffer-exists)
```

Finally, the URLs need to reflect the directory structure too.
```
@@ -255,8 +259,11 @@ Preamble and Postamble are excluded, too."
 
 (defun org-static-blog-get-url (post-filename)
   "Generate a URL to the published POST-FILENAME."
+  (concat
+   (file-name-directory
+     (file-relative-name post-filename org-static-blog-posts-directory))
   (file-name-nondirectory
-   (org-static-blog-matching-publish-filename post-filename)))
+   (org-static-blog-matching-publish-filename post-filename))))
 
 ;;;###autoload
 (defun org-static-blog-publish-file (post-filename)
` 
```

If you guys think its on the good track we can polish it up once I am done with the semantic HTML PR.

**Comment by bastibe** [comment]
Cool! I'll look forward to the PR!

**Comment by neeasade** [comment]
One alternative approach I would like to see is a user provided function that returns the output target. It could take in the existing file path, or the file path + time, then you could return `/path/to/site/2018/05/03/post.html` -- The default value could just be a function that returns `post.html` for existing stuff, but then users could use whatever they like

**Comment by bastibe** [comment]
Cool idea! I like it!

**Comment by justinabrahms** [comment]
I believe this is done now as of #83

**Comment by notbandali** [comment]
I think so too, thanks!  Closing; but feel free to reopen if needed.
