### ISSUE TITLE
Have `index.html` and other `html` files in different locations

### ISSUE THREAD

**Issue by e-eight** [bastibe/org-static-blog#104]
From what I am seeing that currently all the `html` files are published in `org-static-blog-publish-directory`. I was wondering if it would be possible to instead just have the `html` files corresponding to the blog posts be published in the `org-static-blog-publish-directory` and the `index.html` file be published in the parent directory of `org-static-blog-publish-directory`?

**Comment by bastibe** [comment]
There is no built-in functionality for this. But you could probably `advise` `org-static-blog-assemble-index` to use a different `org-static-blog-publish-directory`, which should do the trick.
