### ISSUE TITLE
This project is not referenced on Org's website

### ISSUE THREAD

**Issue by Ambrevar** [bastibe/org-static-blog#11]
I think this project deserves an addition to Org's hall-of-fame: https://orgmode.org/worg/org-blog-wiki.html :)

**Comment by Ambrevar** [comment]
The wiki or this project? :p

**Comment by bastibe** [comment]
To the wiki

**Comment by Ambrevar** [comment]
I tried but it seems that I'm missing access rights to https://code.orgmode.org/bzg/worg.
I followed the guide at https://orgmode.org/worg/worg-git.html.

I made a fork where I've added org-static-blog: https://code.orgmode.org/Ambrevar/worg.

Don't know what I'm doing wrong.

**Comment by bastibe** [comment]
Thank you for trying!
It seems to me that point 9:
> Ask bzg AT gnu.org to be added as a collaborator on the Worg repo.
Is crucial.
Did BZG give you access rights, yet?

**Comment by Ambrevar** [comment]
Where did you read that? O.o
I have sent an e-mail to BZG.

**Comment by Ambrevar** [comment]
Done! :)

**Comment by bastibe** [comment]
Thank you very much!
