### ISSUE TITLE
Last package (20221018.933) is broken. Just a typo.

### ISSUE THREAD

**Issue by gdindi** [bastibe/org-static-blog#112]
Hi,

I just updated the package:
;; Package-Version: 20221018.933
;; Package-Commit: bebd826a7664bd4140ad4d8b592ba1d2c5decd76
and it does not load correctly. 
It seems there is a trailing paren here:
https://github.com/bastibe/org-static-blog/blob/bebd826a7664bd4140ad4d8b592ba1d2c5decd76/org-static-blog.el#L605
I removed and everything seems fine.
Thanks.

**Comment by bastibe** [comment]
Should be fixed in f830e027986df120be4f199f4f36b8f2948f3247

**Comment by gdindi** [comment]
Thanks!
