### ISSUE TITLE
Add a publish-to (eg local/prod) function?

### ISSUE THREAD

**Issue by llaisdy** [bastibe/org-static-blog#128]
Hello!  This is a great repo and I am starting to put together a static site with it.

I would like to use a `publish-to <site>` function, so I could specify the base url -- eg publish to localhost for local testing or mysite.com for production.

If there's already a function in `org-static-blog.el` that does this (or equivalent) (or if there's a better way of deploying locally), please let me know.  Otherwise I'll write one and send in a PR.

Thanks!

**Comment by bastibe** [comment]
org-static-blog renders into any local directory, with a user-defined base url. You could advise the publish function with two different `org-static-blog-publish-directory` and `org-static-blog-publish-title` for your two targets.

I usually run `python -m http.server` in the publish-directory, for local testing.

**Comment by llaisdy** [comment]
Thanks.  Content will be the same, only difference will be `org-static-blog-publish-url`.  I could just (re-)set the variable and call `org-static-blog-publish` but I'm lazy.  I'll do up a PR shortly.
