### ISSUE TITLE
Overwrites other buffers called index.html

### ISSUE THREAD

**Issue by termitereform** [bastibe/org-static-blog#17]
Alright, I think I've got a bug.

In my current set-up of a very simple static site I run, I have the site's main index in the root directory, and the output of `org-static-blog` in a subdirectory:

`sitename\index.html`
`sitename\blog\index.html`

Say that I am editing `sitename\index.html`. I finish my edit, and save the buffer -- but don't *kill* the buffer. 

Say that I then write a new blog post, and save that buffer to `sitename\blog\posts\newpost.org`

If I then run `org-static-blog-publish` to build the blog, without killing the buffer containing `sitename\index.html`, then `org-static-blog-publish` incorrectly overwrites the contents of the `sitename\index.html` buffer with the code that should be going into the file at `sitename\blog\index.html`. The process then automatically saves the result, which essentially destroys the original file.

I thought for a while that I'd just misconfigured the folders, but discovered this morning that this appears to happen regardless of where I put the `index.html` file that I'm editing.

So, for example, from a new Emacs session where I haven't done anything yet, if I create a new buffer and save it as:

`sitename\blog\bug\hello\test\index.html`

And then immediately run `org-static-blog-publish` -- as long as I haven't killed the `sitename\blog\bug\hello\test\index.html` buffer, the file will be overwritten and saved in that weird location. The index file in `sitename\blog\index.html` will be untouched.

I don't know enough about Elisp to know if this is even fixable -- and the obvious solution is "kill your index buffer before building the blog" -- but I thought maybe you should know.

**Comment by bastibe** [comment]
This is indeed a bug, thank you for reporting it!

Can you try changing [line 166](https://github.com/bastibe/org-static-blog/blob/master/org-static-blog.el#L166) from 

```elisp
(buffer-exists (get-buffer (file-name-nondirectory ,file)))
```
to 
```elisp
(buffer-exists (get-buffer ,file))
```

and see if that fixes your issue? (`M-x eval-buffer` or restart emacs for the changes to take effect).

**Comment by termitereform** [comment]
That looks to have fixed it!

I did a couple tests of different scenarios where I've seen that happen, and it's working perfectly now.

[Also, apologies about leaving that other issue open for like 6 months -- I got busy and forgot to close the loop.]

**Comment by bastibe** [comment]
OK, cool, thank you for checking. I'll push the fix to melpa, soon.

[And no worries, there's no rush]
