### ISSUE TITLE
Wrong type argument: listp, #("Welcome" 0 7 (:parent (#0))) error

### ISSUE THREAD

**Issue by BasicObject** [bastibe/org-static-blog#18]
When I issue a M-x org-static-blog-publish I receive the error: 

Wrong type argument: listp, #("Welcome" 0 7 (:parent (#0)))

Contents of 2019-01-08-welcome.org:

    #+title: Welcome
    #+date: <2019-01-08 23:04>
    #+filetags: news
    
    Example blog entry text here

Forgive my ignorance but I'm not sure what I've done wrong here. No html is being exported. I'm using Emacs 25.2.2, Org 9.2 and org-static-blog 1.2.1. Are my Emacs and Org versions too new?

**Comment by BasicObject** [comment]
I added the following to my .emacs:

Under (custom-set-variables:
'(org-static-blog-enable-tags t)

'(package-selected-packages
   (quote
    (bug-hunter org-static-blog...

;; -----------------------------------------------------------------------------
;; Set up blogging in Emacs
;; -----------------------------------------------------------------------------

(setq org-static-blog-publish-title "My Site Name")
(setq org-static-blog-publish-url "https://mysite.com")
(setq org-static-blog-publish-directory "~/Code/mysite/")
(setq org-static-blog-posts-directory "~/Code/mysite/posts/")
(setq org-static-blog-drafts-directory "~/Code/mysite/drafts/")
(setq org-static-blog-enable-tags t)
(setq org-export-with-toc nil)
(setq org-export-with-section-numbers nil)

(setq org-static-blog-page-header
"<meta name=\"author\" content=\"My Name\">
<meta name=\"referrer\" content=\"no-referrer\">
<link href= \"static/style.css\" rel=\"stylesheet\" type=\"text/css\" />
<link rel=\"icon\" href=\"static/favicon.ico\">
<link rel=\"apple-touch-icon-precomposed\" href=\"static/favicon-152.png\">
<link rel=\"msapplication-TitleImage\" href=\"static/favicon-144.png\">
<link rel=\"msapplication-TitleColor\" href=\"#859900\">
<script src=\"static/katex.min.js\"></script>
<script src=\"static/auto-render.min.js\"></script>
<link rel=\"stylesheet\" href=\"static/katex.min.css\">
<script>document.addEventListener(\"DOMContentLoaded\", function() { renderMathInElement(document.body); });</script>
<meta http-equiv=\"content-type\" content=\"application/xhtml+xml; charset=UTF-8\">
<meta name=\"viewport\" content=\"initial-scale=1,width=device-width,minimum-scale=1\">")

(setq org-static-blog-page-preamble
"<div class=\"header\">
  <a href=\"https://mysite.com\">My Site</a>
  <div class=\"sitelinks\">
    <a href=\"https://mysite.com/my-story.html\">My Story</a>
  </div>
</div>")

(setq org-static-blog-page-postamble
"<div id=\"archive\">
  <a href=\"https://mysite.com/archive.html\">Other posts</a>
</div>")
;;; end website code ;;;

In /home/username/.emacs.d/elpa/org-static-blog-20180528.648/org-static-blog.el:

;;; org-static-blog.el --- a simple org-mode based static blog generator

;; Author: Bastian Bechtold
;; URL: https://github.com/bastibe/org-static-blog
;; Package-Version: 20180528.648
;; Version: 1.2.1
;; Package-Requires: ((emacs "24.3"))

;;; Commentary:

;; Static blog generators are a dime a dozen. This is one more, which
;; focuses on being simple. All files are simple org-mode files in a
;; directory. The only requirement is that every org file must have a
;; #+TITLE and a #+DATE, and optionally, #+FILETAGS.

;; This file is also available from marmalade and melpa-stable.

;; Set up your blog by customizing org-static-blog's parameters, then
;; call M-x org-static-blog-publish to render the whole blog or
;; M-x org-static-blog-publish-file filename.org to render only only
;; the file filename.org.

;; Above all, I tried to make org-static-blog as simple as possible.
;; There are no magic tricks, and all of the source code is meant to
;; be easy to read, understand and modify.

;; If you have questions, if you find bugs, or if you would like to
;; contribute something to org-static-blog, please open an issue or
;; pull request on Github.

;; Finally, I would like to remind you that I am developing this
;; project for free, and in my spare time. While I try to be as
;; accomodating as possible, I can not guarantee a timely response to
;; issues. Publishing Open Source Software on Github does not imply an
;; obligation to *fix your problem right now*. Please be civil.

;;; Code:

(require 'org)
(require 'ox-html)

(defgroup org-static-blog nil
  "Settings for a static blog generator using org-mode"
  :version "1.2.1"
  :group 'applications)

(defcustom org-static-blog-publish-url "https://mysite.com"
  "URL of the blog."
  :group 'org-static-blog)

(defcustom org-static-blog-publish-title "My Site Name"
  "Title of the blog."
  :group 'org-static-blog)

(defcustom org-static-blog-publish-directory "~/Code/mysite/"
  "Directory where published HTML files are stored."
  :group 'org-static-blog)

(defcustom org-static-blog-posts-directory "~/Code/mysite/posts/"
  "Directory where published ORG files are stored.
When publishing, posts are rendered as HTML, and included in the
index, archive, tags, and RSS feed."
  :group 'org-static-blog)

(defcustom org-static-blog-drafts-directory "~/Code/mysite/drafts/"
  "Directory where unpublished ORG files are stored.
When publishing, draft are rendered as HTML, but not included in
the index, archive, tags, or RSS feed."
  :group 'org-static-blog)

...omitted because unchanged...

(defcustom org-static-blog-page-header "Customized Name of My Site"
  "HTML to put in the <head> of each page."
  :group 'org-static-blog)

Thank you for your help. It is very much appreciated!

**Comment by bastibe** [comment]
I still don't know the cause of your problem, and haven't been able to reproduce it yet. However, you should not edit org-static-blog.el at all. The customizations in your .emacs are sufficient for that (they overwrite the default values from org-static-blog.el).

Other than that, your config is identical to mine, so that's probably not the problem.

But, my Emacs is newer and my org-mode is older. Would you mind trying to run org-static-blog on Emacs 26.1 with its pre-installed version of org-mode to see if that's the problem? (Once we find the problem, we can hopefully fix it for your current Emacs).

**Comment by BasicObject** [comment]
Reinstalled org-static-blog via package-install to get a default org-static-blog.el back. I'm still receiving the same error so I'm going to install on a different system with emacs default org and report back.

**Comment by BasicObject** [comment]
I had a spare laptop with Ubuntu 16.04. I installed a "fresh" Emacs 24.5.1 with apt and Org 8.2.10 installed by default. I simply reused the .emacs configuration above changing the package repository code to the following:

    (add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/") t)

I replicated the same blog post file, issued a M-x org-static-blog-publish and the site generated. Not sure what it was yet but I'm going to try to fix my other install now.

**Comment by BasicObject** [comment]
Is it possible that when I unintentionally upgraded Org from 8.x to 9.2 the html exporter broke due to [this change](https://orgmode.org/worg/exporters/ox-overview.html)?

**Comment by BasicObject** [comment]
Okay. Got it. On my original setup all I had to do was delete the org 9.2 package folder and export worked. I hope this issue I had helps someone. @bastibe Thank you for your help and for writing [org-static-blog](https://github.com/bastibe/org-static-blog/).

**Comment by bastibe** [comment]
Good to know that there are issues with 9.2, though. Thank you for your bug report, and investigation.
