### ISSUE TITLE
Tagged feeds

### ISSUE THREAD

**Issue by matthewbauer** [bastibe/org-static-blog#2]
Hi,

First off thanks for making this! This is the best blogging solution in org I've been able to find and it's very easy to use.

One feature I would find useful is being able to build up indexes for different tagged post. So I want to be able to have a .xml file (and maybe archive) that lists all of my posts with one tag (say org related posts) and be able to put that in the feed reader. Seems like it should be possible but I haven't been able to look into it yet.

**Comment by bastibe** [comment]
Thank you for your message. This feature sounds really interesting. However, I can tell you right now that I won't have time (in the near future) to implement it.

But, I can tell you how I would go about it, and maybe someone else can do it! Maybe you?

The function `org-static-blog-create-rss` creates RSS feeds. It is really very simple: 

- First, it iterates over all org-static-blog files, and `org-export-as` them one by one, while collecting the publishing dates. 
- Second, it opens the RSS file and writes the (sorted by date) list of exported entries to that file.

Pretty straight-forward.

For your application, that first loop, the one that calls `org-export-as`, would need to collect tags as well as dates. Then, the second part would need to write not just one master file, but one file for each tag. Note that exporting (the first loop) takes quite a long time, so you should try to avoid exporting each entry more than once.

**Comment by bastibe** [comment]
Here's an update on this: In the last few days, I implemented a simple tagging system. You can now specify a list of tags per post, by adding a `#+tags:` header to your org files. These tags are included in the RSS feed as `<category>` tags. Some RSS readers are able to filter RSS items based on these categories.

Does this solve your problem?

**Comment by matthewbauer** [comment]
Yes looks good! Thanks
