### ISSUE TITLE
org-static-blog created a page from the wrong file

### ISSUE THREAD

**Issue by neeasade** [bastibe/org-static-blog#20]
Hello -- I had an org buffer named `rice.org` open somewhere that was not related to my drafts-dir (abusing for static pages) `rice.org` file. When I generated my site, the open buffer of that name got scooped and generated instead of the intended draft page org source file. Just a gotcha to be aware of

**Comment by bastibe** [comment]
Yes, org-static-blog tries to reuse open buffers, for better or worse. I'd be grateful if you implemented a better way in a pull request!
