### ISSUE TITLE
org-static-blog-publish wrong

### ISSUE THREAD

**Issue by luhuaei** [bastibe/org-static-blog#27]
Hi, When I exec `org-static-blog-publish`, prompt wrong  `apply: Wrong type argument: sequencep, org-static-blog-assemble-tags-archive-tag`. 

Finally  discover  the  `(apply 'concat (mapcar tag-tree 'org-static-blog-assemble-tags-archive-tag))` error 

Modify to `(apply 'concat (mapcar 'org-static-blog-assemble-tags-archive-tag tag-tree))`  ;)

**Comment by bastibe** [comment]
Cool, thank you for finding this bug! Would you like to create a pull request for it?

**Comment by luhuaei** [comment]
ok already pull request

**Comment by bastibe** [comment]
Thank you very much!
