### ISSUE TITLE
"#+date:" regex search fails when foreign newline characters are present

### ISSUE THREAD

**Issue by termitereform** [bastibe/org-static-blog#3]
Hello! Thanks for the upgrade to the build process. It's much improved! I've got an unusual bug for you, though -- or maybe just an FYI?

I wrote a post on a Windows machine in Notepad (it was all I had at the time). I sent it to my posts folder, and tried to run `org-static-blog-publish` as usual remotely, without looking at the file first. I received the following error: 

`let: Search failed: "^\\#\\+date:[ ]*<\\([^]>]+\\)>$"`

I re-ran the publish operation immediately without bothering to make any changes to anything, because *that's* how computers work, as we all know, and it gave me the slightly different error: 

`progn: Search failed: "^\\#\\+date:[ ]*<\\([^]>]+\\)>$"`

I checked my config -- I know you've done a few releases this week -- but everything still looked good.

Turns out, those pesky `\M` newline characters from Windows in my post were hosing the search function you're running. Replaced the newlines, saved, and `org-static-blog-publish` completed correctly.

**Comment by bastibe** [comment]
Hi! Thank you for the bug report. That is very strange. I can only assume that the file is opened with the wrong newline mode? Can you tell me the value of your `buffer-file-coding-system`?

**Comment by bastibe** [comment]
I tried to reproduce this bug on my machine: I create a new blog post, and save it with `latin1-dos` as `buffer-file-coding-system` (line endings are now `\r\n`, while all other posts are `\n`). I kill the buffer, then run `org-static-blog-publish`. But it all works as intended, I don't get an error message.

Could there be something else going on on your machine?

**Comment by termitereform** [comment]
Hmm, interesting. I was able to replicate it with a dummy file.

Okay, here's what I've got: 

`buffer-file-coding-system` defaults to `utf-8-unix` in org-mode for me.

Post file's encoding is ANSI (which is the default for Windows Notepad). 

I've attached a test post that threw the error when I tried to publish it -- it wouldn't let me attach it with the .org extension, so I just renamed it .txt

[180325.txt](https://github.com/bastibe/org-static-blog/files/1845462/180325.txt)

**Comment by bastibe** [comment]
Your file worked fine for me. Emacs opens the file in `undecided-dos`.

I tried this again without loading my configuration (run `emacs -Q`, then eval all of org-static-blog, and only my org-static-blog-specific parts of my init.el), and it again worked without issue.

Could you try that on your machine? Just to make sure that there is nothing in your configuration that is interfering here?

**Comment by termitereform** [comment]
This was resolved -- it was an encoding problem on my end.

**Comment by bastibe** [comment]
Thank you for reporting back. I'm glad you were able to resolve your issue.

**Comment by grumblem** [comment]
I'm also getting a similar error, but my files are all UTF-8 encoded. 

The error I get when trying to run org-static-blog-publish:
org-static-blog-get-date: Search failed: "^\\#\\+date:[ ]*<\\([^]>]+\\)>$"

**Comment by bastibe** [comment]
Do all your files contain the `#+date:` header, and if so, can you pinpoint which one of them causes the issue?

**Comment by grumblem** [comment]
They do all contain the  `#+date:` in the header. Actually all new files I create on my computer with Ubuntu seem to cause the error. I have another machine with OSX and everything works perfectly there, so I'm really not sure what the issue is. 

I am attaching a post I just made (as a txt file) that gives me the error when I run org-static-blog-publish.

Thank you for responding to this, and thank you for org-static-blog, I really like it a lot.

[2019-04-15-testing.txt](https://github.com/bastibe/org-static-blog/files/3081387/2019-04-15-testing.txt)

**Comment by bastibe** [comment]
Your file works fine on my computer. If I had to guess, I would say that this is still an encoding issue. Maybe your init.el is in a different encoding?
