### ISSUE TITLE
ox-tufte as a "template" ?

### ISSUE THREAD

**Issue by pseudomyne** [bastibe/org-static-blog#49]
Hi. 
Thank you for your work. I’m planning to make use of it for my blog (test here : https://xavierleleu.ouvaton.org/blog)

Wondered.. Do you think of any trivial way to integrate [ ox-tufte](https://github.com/dakrone/ox-tufte) as a «template» ?
This is alas totally beyond my «hacking» skills.

**Comment by bastibe** [comment]
I have no idea, to be honest. But the only dependency on the regular org-mode export system really is here: https://github.com/bastibe/org-static-blog/blob/master/org-static-blog.el#L521

So if you replace that with ox-tufte that might work. On the other hand, these things typically mostly change the CSS, and embedding your own CSS does not require changing the HTML code at all.

**Comment by pseudomyne** [comment]
Thanks for your answer. I'll add something here if I work further on this.
