### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by bricewge** [bastibe/org-static-blog#50]
Could we get a new release? The last one is going to be 2 years ago and more than half of the total commits (67) aren't incorporated in a release yet.

**Comment by bastibe** [comment]
Goodness me, it has been two years indeed!

I am terribly sorry. I'll get on it right away.

**Comment by bastibe** [comment]
Done. The new version should hit melpa-stable within a day or so.

**Comment by bricewge** [comment]
That was quick! Thank you for `org-static-blog` @bastibe!
