### ISSUE TITLE
org-blog-static-mode should be a minor mode.

### ISSUE THREAD

**Issue by MassimoLauria** [bastibe/org-static-blog#53]
Since all the mode does is to set few keybindings, I don't see the point of having the mode to be a major mode derived from org-mode. It would be cleaner to make it a minor mode. In this way the user would be able to create posts (and drafts, see my PR #52) from any buffer, as long as the minor mode is active.

**Comment by bastibe** [comment]
True, at this point in time, blog posts are just normal org-mode files, and org-static-blog need not derive from org-mode at all. If I remember correctly, this was different in the first versions of org-static-blog.

As it stands at the moment, org-static-blog-mode is not even activated, ever (and neither are the key bindings). However, as per the [Emacs key binding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) only major modes are allowed to use `C-c C-???` key bindings. Additionally, people might be using `org-static-blog-mode`, so we can't remove it.

So... I don't know. I don't think we should remove the existing major mode for backwards compatibility reasons, and I am somewhat doubtful whether the minor mode would solve anything that isn't better solved by manual key bindings.

What to you think on this matter?

**Comment by MassimoLauria** [comment]
Well it does not matter too much to me neither. Indeed for other feature I wanted I did some pull requests. I just thought that going the minor-mode way would have been more standard. 

When I need to create a post/draft I just use M-x and type few letters of the appropriate command.  I guess I will close this issue then.
