### ISSUE TITLE
Get rid of links on standalone pages

### ISSUE THREAD

**Issue by GrinDeg** [bastibe/org-static-blog#64]
I don't want to have links which go to the same page, like each blog plost's `<h1>` is a link to itself.
Is it possible to remove them? 
UPD:
I tried to remove them, but it also removed them from index page

**Comment by bastibe** [comment]
Not at the moment, no. Standalone pages are just blog posts that aren't sorted into the archive and feed. If you want to have truly standalone pages, you might want to create them as plain HTML files, outside of org-static-blog.

**Comment by GrinDeg** [comment]
Ok, thanks for the answer
