### ISSUE TITLE
Change URL patterns

### ISSUE THREAD

**Issue by aciceri** [bastibe/org-static-blog#69]
I've never used `org-static-blog` and I just started porting my blog (which uses only `org-export`).
I'm a Emacs beginner but, copying snippets of code around the web, I was able to write this:

```
(defun my-org-export-output-file-name (orig-fun extension &optional subtreep pub-dir)
  (if (string-match "posts/\\'" pub-dir)
      (let ((path (buffer-file-name (buffer-base-buffer))))
	(save-match-data (and (string-match "posts/\\([^@]+\\)\\.org\\'" path)
			      (setq filename (match-string 1 path))))
	(if (equal filename "index")
	    (concat pub-dir "/index.html")
	  (progn
	    (make-directory (concat pub-dir filename))
	    (concat pub-dir filename "/index.html")
	    )))
    (apply orig-fun extension subtreep pub-dir nil)))

(advice-add 'org-export-output-file-name :around #'my-org-export-output-file-name)
```

The idea is that if I have a post file `my-post.org` then it should be published as `https://myblog.com/posts/my-post/index.html`.
One problem, for example, is that `org-static-blog` creates pages for the tags, there should be need of an analogue for the tags.
Moreover, since I don't know this project, I don't think I can predict all the related issues.
So before I try to invent a not so elegant workaround I would like to know if:
1. is there already a way using `org-static-blog`?
2. is there interest to have a way? In the case, if I succeed doing this in a decent way I could consider a pull request.

**Comment by bastibe** [comment]
I am not sure I understand your questions completely. Please correct me if I'm misinterpreting something.

org-static-blog takes a bunch of org files in a `posts` directory, and renders them as HTML in the main directory. In addition, it assembles an `index.html`, an `archive.html`, an RSS feed, a `tags.html`, and one HTML page per tag. 

Each file in `posts` has a date, and optionally a number of tags. For example, one of my recent blog posts started with

```org-mode
#+title: How to Write a Dissertation
#+date: <2020-05-27 18:11>
#+filetags: computers emacs workflow
```

(I realize that I should put an example like this in the README. I'll do that right away.)

Does this answer your questions?

**Comment by aciceri** [comment]
Sorry if I wasn't clear, I meant that I don't like to have all the html pages in the main directory, I would prefer to the posts and the tags pages in dedicated folders.
It's a matter of personal tastes, but I would prefer that my urls would be something like this:

* http://www.myblog.com/posts/my-post/ for posts
* http://www.myblog.com/tags/my-tag/ for tags
* http://www.myblog.com/rss/ for the feed
* http://www.myblog.com/archive/ for the archive
* http://www.myblog.com/ for the main page (the actual `index.html`)

In this way, evey generated html page need to be called `index.html` and be placed inside a specific folder.

I was able to get a similar behaviour using only `org`, I can try to get something similar with `org-static-blog`.
What do you think?

**Comment by bastibe** [comment]
I think this is possible. There are customizable variables for pretty much every file name and directory. You might need to have "file names" such as "archive/archive.html" and create the enclosing "archive" by hand, but apart from that it should all work.

**Comment by aciceri** [comment]
I managed to get my goal, I simply added to my publish script the following lines:

```
(setq org-static-blog-tags-file "tag/index.html"
      org-static-blog-archive-file "archive/index.html"
      org-static-blog-rss-file "rss/index.rss")

(advice-add 'org-static-blog-generate-post-path
	    :around #'(lambda (orig-fun &rest args)
  (let* ((filename (car args))
	 (new-filename (concat "post/"
			       (file-name-sans-extension filename)
			       "/index.html")))
    (apply orig-fun (cons new-filename (cdr args))))))

(defun org-static-blog-assemble-tags ()
  (org-static-blog-assemble-tags-archive)
  (dolist (tag (org-static-blog-get-tag-tree))
    (org-static-blog-assemble-multipost-page
     (concat org-static-blog-publish-directory "tag/" (downcase (car tag)) "/index.html")
     (cdr tag)
     (concat "<h1 class=\"title\">" (org-static-blog-gettext 'posts-tagged) " \"" (car tag) "\":</h1>"))))

(defun org-static-blog-post-taglist (post-filename)
  (let ((taglist-content ""))
    (when (and (org-static-blog-get-tags post-filename) org-static-blog-enable-tags)
      (setq taglist-content (concat "<a href=\""
                                    (org-static-blog-get-absolute-url org-static-blog-tags-file)
                                    "\">" (org-static-blog-gettext 'tags) "</a>: "))
      (dolist (tag (org-static-blog-get-tags post-filename))
        (setq taglist-content (concat taglist-content "<a href=\""
                                      (org-static-blog-get-absolute-url (concat "tag/" (downcase tag) "/"))
                                      "\">" tag "</a> "))))
    taglist-content))

(advice-add 'org-static-blog-get-post-url
	    :around #'(lambda (orig-fun &rest args)
			(file-name-directory (apply orig-fun args))))

```

I set three variables, `advice`d and overwrote some functions.
This approach seems to work, all the internal links work. Maybe is not so elegant and I don't think it can be easily integrated.
I noticed that some links are extended e.g. `/archive/index.html` instead of simply `/archive/` but at least for posts and tags I solved this problem.
Solving this would require the overwriting of other functions (pretty long) and since it's not so important I think I'll leave like this.

You can close the issue, my approach cannot be easily integrated in the `org-static-blog` and I don't understand if someone might be interested into this.
Otherwise, if someone is interested, I can consider to try to integrate it as optional configurable variable, since I don't think it's would be great to break the links of the current blogs.

**Comment by bastibe** [comment]
Cool! I love how malleable Emacs is!

If anyone is interested in this feature, feel free to re-open the issue!
