### ISSUE TITLE
Datetime strings in RSS feed are not properly RFC-822 formatted

### ISSUE THREAD

**Issue by janw** [bastibe/org-static-blog#71]
My feed reader just tripped over the datetime strings used for `lastBuildDate` and `pubDate` in the RSS feed of your site, bastibe.de. Apparently `format-time-string` formats the dates according to the system locale, when not specified otherwise. Thus specifically the month of May comes back as Mai with a German locale setting, leading to an invalid feed:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fbastibe.de%2Frss.xml

It should be ensured that settings `LC_TIME=en`, and `(setq system-time-locale "en")` are used when rendering.

Cheers 👋

**Comment by bastibe** [comment]
Hi Jan! How are you?

Thank you for the bug report. And even more so for the proposed solution, as I had wondered about this problem for a while now, but hadn't found a solution yet.
