### ISSUE TITLE
Wrong number of arguments error when exporting with org-static-blog-enable-tags t

### ISSUE THREAD

**Issue by Scrofff** [bastibe/org-static-blog#76]
I'm using org-static-blog-20201117.906. I created the file

`#+title: First post
#+date: <2020-11-18 08:08>
#+filetags: test random

I am trying out ~org-static-blog~ for the first time. I want to blog a bit, and I like org so maybe this is the correct solution for me.`

and run org-static-blog-publish, which results in the error
`org-static-blog-assemble-multipost-page: Wrong number of arguments: (lambda (dir filename) "Concat filename to another path interpreted as a directory." (concat (file-name-as-directory dir) filename)), 4`

The post is correctly exported and the files archive.html, index.html, rss.xml, and tags.html are created correctly but tag-test.html and tag-random.html are not created.

All works correctly when org-static-blog-enable-tags is set to nil

**Comment by Scrofff** [comment]
I tried generating the blog using the 1.4.0 release and it works fine

**Comment by bastibe** [comment]
This must be a regression from #75.

Would you like to create a pull request to fix it?

**Comment by adithyaov** [comment]
This is my fault. My apologies. Will send a fix.
