### ISSUE TITLE
Many articles create rss file too big

### ISSUE THREAD

**Issue by hefistion** [bastibe/org-static-blog#84]
First of all, thank you for your work

I have migrated my blog https://elblogdelazaro.gitlab.io to org-static-blog.

I have many articles created and the feed it creates is very heavy (1.2 MB), could it be made that only the last ten blog entries are generated?

Thank you.

**Comment by bastibe** [comment]
There is currently no functionality for limiting the scope of the RSS feed. But if you'd like to contribute a pull request, it shouldn't be too hard to implement a simple first-100-entries in `org-static-blog-assemble-rss`.

Even better would be support for paged feeds, but that would certainly be more effort.

**Comment by hefistion** [comment]
Thanks for answering

My knowledge of lisp is nil, otherwise I would have gladly contributed, I am simply an org.mode user.

So far I have solved it by manually editing the file.

Thank you very much for your work and your time. Cheers
