### ISSUE TITLE
Drafts are published to directory relative to posts directory instead of drafts directory

### ISSUE THREAD

**Issue by petergil** [bastibe/org-static-blog#86]
After the update in #83 draft entries are published to their position relative to the post directory since the new implementation does not take drafts into account.

This means that if you have

```lisp
(setq org-static-blog-publish-directory "~/projects/blog/")
(setq org-static-blog-posts-directory "~/projects/blog/posts/")
(setq org-static-blog-drafts-directory "~/projects/blog/drafts/")
```

(like in the readme setup) and a draft named `~/projects/blog/drafts/test.org` the html file that will be generated is `~/projects/blog/../drafts/test.html`.

A simple (but not elegant) fix would be to just do something like

```lisp
(let ((post-base-dir (cond ((string-prefix-p org-static-blog-posts-directory post-filename) org-static-blog-posts-directory)
                           ((string-prefix-p org-static-blog-drafts-directory post-filename) org-static-blog-drafts-directory))))
  (concat (file-name-sans-extension (file-relative-name post-filename post-base-dir))
	      ".html"))
```

instead.

**Comment by bastibe** [comment]
Thank you for reporting this bug. True, I didn't consider drafts in #83.

Would you like to contribute your fix as a pull request?

**Comment by petergil** [comment]
Sure, I sent one in now.

**Comment by petergil** [comment]
Doh, I misclicked when leaving a comment..

What I was going to say is that I thought I should mention that with my pull request if the `drafts` directory is a subdirectory of the `posts` directory any drafts will be published relative to the 'posts' directory (so if you have 'posts/drafts/foo.org' it will be published to '/drafts/foo.html').

My thinking there is that if you have a setup like that, it is probably on purpose, and you do want that hierarchy for your drafts when they get published.

**Comment by bastibe** [comment]
That sounds reasonable, actually.

**Comment by bastibe** [comment]
Since `~/Personal/drafts` is not a default value of org-static-blog itself, this must be something you set somewhere else in your configuration.
