### ISSUE TITLE
Warning : 'the function ‘list-length’ is not known tobe defined.'

### ISSUE THREAD

**Issue by fenix011** [bastibe/org-static-blog#88]
Just to mention a *Warning*

```
In end of data:
org-static-blog.el:861:1:Warning: the function ‘list-length’ is not known to
    be defined.
```
Compile-log, while installation.

Hope it helps...

**Comment by bastibe** [comment]
I bet this function was renamed to `cl-list-length` in some recent version of Emacs. This probably didn't come up as a bug, because no-one ever uses `org-static-blog-open-previous-post` and `org-static-blog-open-next-post`.

Would you like to contribute a pull request fixing these two functions?
