### ISSUE TITLE
customize index page

### ISSUE THREAD

**Issue by bderembl** [bastibe/org-static-blog#90]
Hi there,
great package thank you.

I was wondering if one could customize the index page a bit like adding a description of the blog just below the header.

maybe a pinned post (without the date)?
thanks

**Comment by bastibe** [comment]
There is currently no functionality for that. Perhaps it would be cool to add hooks or something to e.g. `org-static-blog-assemble-index` that would enable such additions. Alternatively, you can probably advise `org-static-blog-assemble-index` to insert some custom content.

**Comment by bderembl** [comment]
Would you consider a PR with a new variable org-static-blog-index-front-matter defined here 
https://github.com/bastibe/org-static-blog/blob/a66d1e43882978a9da82c033a809765061c71052/org-static-blog.el#L150
and then add this as the last argument in 
org-static-blog-assemble-index
here
https://github.com/bastibe/org-static-blog/blob/a66d1e43882978a9da82c033a809765061c71052/org-static-blog.el#L595

**Comment by bastibe** [comment]
Great work, thank you!
