### ISSUE TITLE
Publish not working all the time

### ISSUE THREAD

**Issue by magthe** [bastibe/org-static-blog#93]
I'm having issues with `org-static-blog-publish` failing with the following error message every now and then.

```
helm-M-x-execute-command: Wrong type argument: stringp, nil
```

There seems to be no pattern to it failing. Am I alone in seeing this? My experience with elisp is limited, so where should I start trying to debug this?

My config looks like this

```
(setq
 org-static-blog-drafts-directory "~/Private/tmp/tst-org-static/drafts"
 org-static-blog-enable-tag-rss t
 org-static-blog-enable-tags t
 org-static-blog-posts-directory "~/Private/tmp/tst-org-static/posts"
 org-static-blog-publish-directory "~/Private/tmp/tst-org-static"
 org-static-blog-publish-title "Magnus web site"
 org-static-blog-publish-url "https://magnus.therning.org/"
 org-export-with-toc nil
 org-export-with-section-numbers nil
 )
```

My `(org-version)`: 9.4.4

**Comment by bastibe** [comment]
I have seen errors like this if an org-file contains things that can't be exported for some reason. Try tracking down the offending post, and see if there is some part of it that org can't export.
