### ISSUE TITLE
Switch from ox-publish to org-static-blog

### ISSUE THREAD

**Issue by xgqt** [bastibe/org-static-blog#97]
Hi!

Thanks for great package.
Recently I switched from ox-publish & ox-rss to org-static-blog. Works very nice.
Link: https://gitlab.com/xgqt/blog

You can also add this link to "Other org-static-blog blogs:".

Thanks :D

**Comment by bastibe** [comment]
Cool, thank you!

If you'd like your blog to be linked in the README, feel free to create a pull request!
